<div class="container form-user">
  			
  		<div>
    		<?php $this->flash->output(); ?>
  			<h1>Redeem Code here!</h1>
  			
  			<?php echo $this->tag->form('index/redeem'); ?>
			  <div class="form-group">
			    <label>User ID/Phone Number</label>
			    <?php echo $form->render('userid', ['placeholder' => '08131107274', 'class' => 'form-control']); ?>
			  </div>
			  <div class="form-group">
			    <label>Reward Code</label>
			    <?php echo $form->render('reward_code', ['placeholder' => 'OVOREWARD', 'class' => 'form-control']); ?>
			  </div>
			  <button type="submit" class="btn btn-primary btn-block">Redeem</button>
			<?php echo $this->tag->endForm(); ?>
  		</div>	

  	</div>